// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/app-link/app-link.vue')['default']
    Chart: typeof import('./src/components/chart/chart.vue')['default']
    Counter: typeof import('./src/components/hello/Counter.vue')['default']
    Hello: typeof import('./src/components/hello/Hello.vue')['default']
    Result: typeof import('./src/components/result/index.vue')['default']
  }
}

export { }
