export { default as LayoutHeader } from "./components/layout-header.vue";
export { default as LayoutFooter } from "./components/layout-footer.vue";
export { default as PageLayout } from "./components/page-layout.vue";
export { default as PageView } from "./components/page-view.vue";
export { default as PageHeader } from "./components/page-header.vue";
export { default as PageBreadcrumb } from "./components/page-breadcrumb.vue";
export { default as Page } from "./components/page.vue";
export { default as PageIframe } from "./components/page-iframe.vue";
export { default as Layout } from "./layout.vue";
