export const TOKEN_KEY = "TOKEN";
export const ACCESS_TOKEN_KEY = "ACCESS_TOKEN";
export const REFRESH_TOKEN_KEY = "REFRESH_TOKEN";
export const VUE_ADMIN_CACHE = "VUE_ADMIN_CACHE";
export const API_SERVICE_CACHE = "API_SERVICE_CACHE";

export const ERROR_SERVER_UNREACHABLE = "ERR_SERVER_UNREACHABLE";
export const ERROR_NETWORK_DISCONNECTED = "ERR_NETWORK_DISCONNECTED";

export const ENCRYPT_KEY = "DfKDfT8S2eLkrEz0JKrBaejd";
export const ENCRYPT_IV = "B206F28A";
